app/main/__init__.py
'''

    主視圖藍圖初始化

    created date : 2021/10/05
    created by : jay

    update date : 2021/10/21
    update by : jay

'''

from flask import Blueprint

# ----- 自訂函式 -----
from ..model import Permission

main = Blueprint('main', __name__)

@main.app_context_processor
def inject_permission():
    ''' 在模板 context 中加入 Permission類別 '''
    return dict(Permission = Permission)

from . import views, errors

app/main/views.py
'''

    主視圖程式

    created date : 2021/10/05
    created by : jay

    last update date : 2021/10/26
    update by : jay

'''

from flask import render_template, session, request, redirect, url_for, abort, current_app, make_response
from flask.helpers import flash
from flask_login import login_required, current_user
from datetime import datetime

# ----- 自訂函式 -----
from . import main
from ..model import User, Role, Post, Permission, Comment
from .. import db
from ..decorators import admin_required, permission_required

@main.route('/', methods = ['GET', 'POST'])
def index():

    if request.method == 'POST' and current_user.can(Permission.WRITE):
        post_data = request.form.get('post')
        is_private = request.form.get('is_private')
        if is_private == 'on':
            post = Post(body = post_data, author = current_user._get_current_object(), is_private = True)
        else:
            post = Post(body = post_data, author = current_user._get_current_object())
        db.session.add(post)
        db.session.commit()

        return redirect(url_for('main.index'))

    show_posts = 'all'
    if current_user.is_authenticated:
        show_posts = request.cookies.get('show_posts', 'all')
    
    if show_posts == 'following':
        query = current_user.following_posts.filter(Post.is_private == False)
    elif show_posts == 'all':
        query = Post.query.filter_by(is_private = False)
    elif show_posts == 'private':
        query = current_user.posts.filter_by(is_private = True)

    page = request.args.get('page', 1, type=int)
    pagination = query.order_by(Post.timestamp.desc()).paginate(page, per_page = current_app.config['POSTS_PER_PAGE'], error_out = False)
    posts = pagination.items
    

    return render_template('main/index.html', posts = posts, pagination = pagination, show_posts = show_posts)

@main.route('/all')
@login_required
def show_all_posts():
    ''' 顯示所有文章 '''

    resp = make_response(redirect(url_for('main.index')))
    resp.set_cookie('show_posts', 'all', max_age=30 * 24 * 60 * 60)    # 30 days
    return resp

@main.route('/following_posts')
@login_required
def following_posts():
    ''' 顯示所有追蹤的文章 '''

    resp = make_response(redirect(url_for('main.index')))
    resp.set_cookie('show_posts', 'following', max_age=30 * 24 * 60 * 60)
    return resp

@main.route('/private')
@login_required
def private_posts():
    ''' 顯示所有私人文章 '''

    resp = make_response(redirect(url_for('main.index')))
    resp.set_cookie('show_posts', 'private', max_age= 30 * 24 * 60 * 60)

    return resp

@main.route('/user/<username>')
def user(username : str):
    ''' 使用者個人資訊頁面 '''

    now = datetime.utcnow()

    user = User.query.filter(User.username == username).first()
    if user is None:
        abort(404)
    
    if user == current_user:
        posts = user.posts.order_by(Post.timestamp.desc()).all()
    else:
        posts = user.posts.filter_by(is_private = False).order_by(Post.timestamp.desc()).all()
    return render_template('main/user.html', user = user, now = now, posts = posts)

@main.route('/edit-profile', methods = ['GET', 'POST'])
@login_required
def edit_profile():
    ''' 編輯使用者個人資訊頁面 '''

    if request.method == 'POST':
        current_user.name = request.form.get('name')
        current_user.location = request.form.get('location')
        current_user.about_me = request.form.get('about_me')
        db.session.add(current_user._get_current_object())
        db.session.commit()
        flash('個人檔案已經更新')
        return redirect(url_for('main.user', username = current_user.username))

    form_datas = {
    'form_name' : current_user.name if current_user.name else '',
    'form_location' : current_user.location if current_user.location else '',
    'form_about_me' : current_user.about_me if current_user.about_me else '',
    }

    return render_template('main/edit_profile.html', **form_datas)


@main.route('/edit-profile/<int:id>', methods = ['GET', 'POST'])
@login_required
@admin_required
def edit_profile_admin(id):
    ''' 管理員編輯個人資料頁面 '''
    user = User.query.get_or_404(id)
    if request.method == 'POST':
        form = request.form
        user.email = form.get('email')
        user.username = form.get('username')
        if int(form.get('role')):
            user.role = Role.query.get(int(form.get('role')))

        print(form.get('role'))
        print(bool(int(form.get('role'))))
        user.name = form.get('name')
        user.location = form.get('location')
        user.about_me = form.get('about_me')
        db.session.add(user)
        db.session.commit()
        flash('修改成功')
        return redirect(url_for('main.user', username = user.username))
    
    roles = [(role.id, role.name) for role in Role.query.order_by(Role.name).all()]
    form_datas = {
        'form_email' : user.email,
        'form_username' : user.username,
        'form_name' : user.name if user.name else '',
        'form_location' : user.location if user.location else '',
        'form_about_me' : user.about_me if user.about_me else '',
        'roles' : roles
        }

    return render_template('main/edit_profile_admin.html', user = user, **form_datas)


@main.route('/post/<int:id>', methods = ['GET', 'POST'])
def post(id):
    ''' 特定文章頁面 '''

    post = Post.query.get_or_404(id)

    if request.method == 'POST':
        if not current_user.is_authenticated:
            flash('請先登入')
            return redirect(url_for('auth.login'))
        comment_data = request.form.get('comment')
        comment = Comment(body = comment_data, post = post, author = current_user._get_current_object())
        db.session.add(comment)
        db.session.commit()
        flash('留言已送出')
        return redirect(url_for('main.post', id = post.id))

    page = request.args.get('page', 1, type=int)
    
    pagination = post.comments.order_by(Comment.timestamp.desc()).paginate(page, per_page = 5, error_out = False)

    comments = pagination.items

    return render_template('main/post.html', posts = [post], comments = comments, pagination = pagination)


@main.route('/edit/<int:id>', methods = ['GET', 'POST'])
@login_required
def edit(id):
    ''' 修改文章頁面 '''

    post = Post.query.get_or_404(id)

    if current_user != post.author and not current_user.can(Permission.ADMIN):
        abort(403)

    if request.method == 'POST':
        post_data = request.form.get('post')
        is_private = request.form.get('is_private')
        post.body = post_data
        if is_private == 'on':
            post.is_private = True
        else:
            post.is_private = False

        db.session.commit()

        flash('文章修改完成')
        return redirect(url_for('main.post', id =  post.id))

    return render_template('main/edit_post.html', post = post)

@main.route('/delete/<int:id>', methods = ['POST'])
@login_required
def delete(id):
    ''' 刪除貼文視圖 '''

    post = Post.query.get_or_404(id)

    if current_user != post.author and not current_user.can(Permission.ADMIN):
        abort(403)

    if request.method == 'POST':
        db.session.delete(post)
        db.session.commit()

        flash('刪除成功')
    
    return redirect(url_for('main.index'))

    


@main.route('/follow/<username>')
@login_required
@permission_required(Permission.FOLLOW)
def follow(username):
    ''' 使用者追隨視圖 '''

    user = User.query.filter_by(username = username).first()

    if not user:
        flash('無效的使用者')
        return redirect(url_for('main.index'))
    if current_user.is_following(user):
        flash('你已經關注該使用者')
        return redirect(url_for('main.user', username = username))
    
    current_user.follow(user)
    db.session.commit()
    flash(f'開始關注 {username} ')

    return redirect(url_for('main.user', username = username))


@main.route('/unfollow/<username>')
@login_required
def unfollow(username):
    ''' 解除關注視圖 '''

    user = User.query.filter_by(username = username).first()

    if not user:
        flash('無效的使用者')
        return redirect(url_for('main.index'))
    
    if not current_user.is_following(user):
        flash('錯誤')
        return redirect(url_for('main.user', username = username))

    current_user.unfollow(user)

    flash(f'你不再關注 {username} 了')
    return redirect(url_for('main.user', username = username))


@main.route('/following/<username>')
def following(username):
    ''' 顯示使用者關注的人 '''

    user = User.query.filter_by(username = username).first()

    if not user:
        flash('無效的使用者')
        return redirect(url_for('main.index'))
    
    page = request.args.get('page', 1, type=int)
    pagination = user.following.paginate(page, per_page = 10, error_out = False)

    follows = [{'user' : item.following, 'timestamp' : item.timestamp} for item in pagination.items]

    return render_template('main/follow.html', user = user, title = f"{ user.username } 關注的人", endpoint = 'main.following', pagination = pagination, follows = follows)

@main.route('/followers/<username>')
def followers(username):
    ''' 顯示關注使用者的人 '''

    user = User.query.filter_by(username = username).first()

    if not user:
        flash('無效的使用者')
        return redirect(url_for('main.index'))
    
    page = request.args.get('page', 1, type=int)
    pagination = user.followers.paginate(page, per_page = 10, error_out = False)

    follows = [{'user' : item.follower, 'timestamp' : item.timestamp} for item in pagination.items]

    return render_template('main/follow.html', user = user, title = f"關注 { user.username } 的人", endpoint = 'main.followers', pagination = pagination, follows = follows)


@main.route('/modrate')
@login_required
@permission_required(Permission.MODERATE)
def modrate():
    ''' 管理留言 '''

    page = request.args.get('page', 1, type=int)
    pagination = Comment.query.join(Post, Post.id == Comment.post_id).filter(Post.is_private == False).order_by(Comment.timestamp.desc()).paginate(page, per_page = 10, error_out = False)
    comments = pagination.items

app/templates/main/_comments.html
<ul class="comments">
    {% for comment in comments %}
    <li class="comment">
        <div class="comment-thumbnail">
            <a href="{{ url_for('.user', username=comment.author.username) }}">
                <img class="img-rounded profile-thumbnail" src="{{ comment.author.gravatar(size=40) }}">
            </a>
        </div>
        <div class="comment-content">
            <div class="comment-date">{{ moment(comment.timestamp).fromNow() }}</div>
            <div class="comment-author"><a href="{{ url_for('.user', username=comment.author.username) }}">{{ comment.author.username }}</a></div>
            <div class="comment-body">
                {% if comment.disabled %}
                    <p>
                        <i>此留言已經被管理員禁止</i>
                    </p>
                {% endif %}
                {% if current_user.can(Permission.MODERATE) or not comment.disabled %}
                    {{ comment.body }}
                {% endif %}
            </div>
            {% if current_user.can(Permission.MODERATE) %} 
                {% if comment.disabled %}
                    <a href="{{ url_for('main.enable', id = comment.id, page = page) }}">
                        <span class="badge rounded-pill bg-success">解除禁止</span>
                    </a>
                {% else %} 
                    <a href="{{ url_for('main.disabled', id = comment.id, page = page) }}">
                        <span class="badge rounded-pill bg-danger">禁止此留言</span>
                    </a>
                {% endif %} 
            {% endif %}

        </div>
    </li>
    {% endfor %}
</ul>

app/templates/main/_macros.html
<!--

    分頁功能 巨集

-->

{% macro pagination_widget(pagination, endpoint, is_top = false) %}
<nav>
    <ul class="{% if is_top %} pagination justify-content-end pagination-sm {% else %} pagination justify-content-center {% endif %}">
      <li class="{% if not pagination.has_prev %} page-item disabled {% else %} page-item {% endif %}">
        <a class="page-link" href="{% if pagination.has_prev %} {{url_for(endpoint, page = pagination.page - 1, **kwargs) }} {% else %} # {% endif %}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li> 

      {% for p in pagination.iter_pages(left_edge=2, left_current=2, right_current=2, right_edge=2) %}
        {% if p %} 
          {% if p == pagination.page %} 
            <li class="page-item active"><a class="page-link" href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a></li>
          {% else %} 
          <li class="page-item"><a class="page-link" href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a></li>
          {% endif %}

        {% else %} 
          <li class="page-item disabled"><a class="page-link" href="#">&hellip;</a></li>
        {% endif %}

      {% endfor %}

      <li class="{% if not pagination.has_next %} page-item disabled {% else %} page-item {% endif %}">
        <a class="page-link" href="{% if pagination.has_next %} {{url_for(endpoint, page = pagination.page + 1, **kwargs) }} {% else %} # {% endif %}" aria-label="Previous">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
    </ul>
</nav>
{% endmacro %}

app/templates/main/_post.html
<!-- 貼文串模板 -->

<ul class="posts">
    {% for post in posts %} 
      <li class="post">
        <div class="profile-thumbnail">
          <a href="{{ url_for('main.user', username = post.author.username) }}">
            <img class="img-rounded profile-thumbnail rounded-circle" src="{{ post.author.gravatar(size=40) }}">
          </a>
        </div>
        <div class="post-content">
          <div class="post-date">{{ moment(post.timestamp).fromNow() }} {{ moment(post.timestamp).format('YYYY-MM-DD') }}</div>
          <div class="post-author">
            <a href="{{ url_for('main.user', username=post.author.username) }}">
              {{ post.author.username }}
              {% if post.is_private %} 
                <span class="badge rounded-pill bg-info text-dark">Private</span>
              {% endif %}
            </a>
          </div>
          <div class="post-body">{{ post.body }}</div>
          <div class="post-footer">
            <div class="gap-3 d-flex justify-content-md-end">
              {% if current_user == post.author %}

                <a href="{{ url_for('main.edit', id = post.id) }}">
                  <span class="badge rounded-pill bg-secondary">Edit</span>
                </a>

              {% endif %}
              
              
              <a href="{{ url_for('main.post', id = post.id) }}">
                <span class="badge rounded-pill bg-warning text-dark">{{ post.comments.count() }} 個留言</span>

              </a>
             
            </div>
            
          </div>
        </div>
      </li>
    {% endfor %}
</ul>

app/templates/main/_user.html
<ul class="users">
    {% for user in users %} 
      <li class="user">
        <div class="profile-thumbnail">
          <a href="{{ url_for('main.user', username = user.username) }}">
            <img class="img-rounded profile-thumbnail rounded-circle" src="{{ user.gravatar(size=40) }}">
          </a>
        </div>
        <div class="user-content">
            <div class="user-date">{{ moment(user.member_since).format('YYYY-MM-DD') }} 加入</div>  
            <div class="username">
                <a href="{{ url_for('main.user', username=user.username) }}">
                {{ user.username }}
                </a>
            </div>
            {% if user.location %}
            <div class="user-body">
                來自 <a href="http://maps.google.com/?q={{ user.location }}" target="_blank"> {{ user.location }}</a>
            </div>
            {% endif %}
            <div class="user-footer">
                {% if current_user.can(Permission.ADMIN) %} 
                <div class="gap-3 d-flex justify-content-md-end">
                    <a href="{{ url_for('main.edit_profile_admin', id = user.id) }}">
                        <span class="badge rounded-pill bg-warning text-dark">Edit [ADMIN]</span>
                    </a>
                </div>
                {% endif %}
            </div>
        </div>
      </li>
    {% endfor %}
</ul>

app/templates/main/edit_post.html
{% extends 'basic.html' %} 

{% block head %}
    {{ super() }}
    <link href="{{ url_for('static', filename = 'css/post.css') }}" rel="stylesheet">
{% endblock %}
{% block page_content %}
    <div class="page-header">
        <h1>編輯文章</h1>
    </div>
    <div class="page">
        
        <div class="form-content">
            <form class="row g-3" action="{{ url_for('main.edit', id = post.id) }}" method="POST">
              <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
              <div class="mb-3 row">
                  <label for="exampleFormControlTextarea1" class="form-label">在想什麼</label>
                  <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name = 'post' required>{{ post.body }}</textarea>
              </div>
                <div class="form-check">
                  <input type="checkbox" class="form-check-input" id="exampleCheck1" name="is_private" {% if post.is_private %} checked {% endif %}>
                  <label class="form-check-label" for="exampleCheck1" title="設為私人貼文代表只有本人能看到貼文">設為私人貼文</label>
                </div>
                
                <div class="mb-3">
                  <button class="btn btn-primary" type="submit">修改</button>
                </div>
            </form> 
        </div> 

        <div class="mb-3">
            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
                刪除貼文
            </button>

            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <form action="{{ url_for('main.delete', id = post.id) }}" method="post">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                    <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">刪除貼文</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                        確定要刪除此貼文嗎?
                        </div>
                        <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">取消</button>
                        <button type="submit" class="btn btn-primary">確定</button>
                        </div>
                    </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/main/edit_profile.html
<!--

    編輯使用者詳細資訊頁面

    created date : 2021/10/21
    created by : jay

-->

{% extends 'basic.html' %} 

{% block title %} Edit Profile {% endblock %} 

{% block page_content %} 
    <div class = 'page-header'>
        <h1>編輯你的個人資訊</h1>
    </div>
    <div class="page">
        <form class="row g-3" action="{{ url_for('main.edit_profile') }}" method="POST">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <div class="mb-3">
                <label for="username" class="form-label">真實名稱</label>
                <input type="text" class="form-control" id="name" name="name" value="{{ form_name }}" required>
            </div>
            <div class="mb-3">
                <label for="username" class="form-label">居住地</label>
                <input type="text" class="form-control" id="location" name="location" value="{{ form_location }}" required>
            </div>
            <div class="mb-3">
                <label for="exampleFormControlTextarea1" class="form-label">關於我</label>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name = 'about_me'>{{ form_about_me }}</textarea>
              </div>
            <div class="col-12">
              <button class="btn btn-primary" type="submit">送出</button>
            </div>
        </form>
    </div>
{% endblock %}

app/templates/main/edit_profile_admin.html
<!--

    管理員編輯使用者資訊頁面

    created date : 2021/10/21
    created by : jay

-->

{% extends 'basic.html' %} 

{% block title %} Edit Profile Admin {% endblock %} 

{% block page_content %} 
    <div class="page-header">
        <h1>編輯使用者資訊 (Admin)</h1>
    </div>

    <div class="page">
        <form class="row g-3" action="{{ url_for('main.edit_profile_admin', id = user.id) }}" method="POST">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Email</label>
                <input type="email" class="form-control" id="exampleInputEmail1" name="email" value="{{ form_email }}" aria-describedby="emailHelp" required>
            </div>
            <div class="mb-3">
                <label for="username" class="form-label">使用者名稱</label>
                <input type="text" class="form-control" id="username" name="username" value="{{ form_username }}" required>
            </div>
            <div class="col-md-4">
                <label for="inputState" class="form-label">目前權限: {{ user.role.name }}</label>
            
                <select class="form-select" aria-label="Default select example" name="role">
                    <option selected value="0">使用者權限</option>
                    {% for role in roles %} 
                    <option value="{{ role[0] }}">{{ role[1] }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-3">
                <label for="username" class="form-label">真實名稱</label>
                <input type="text" class="form-control" id="name" name="name" value="{{ form_name }}">
            </div>
            <div class="mb-3">
                <label for="username" class="form-label">居住地</label>
                <input type="text" class="form-control" id="location" name="location" value="{{ form_location }}">
            </div>
            <div class="mb-3">
                <label for="exampleFormControlTextarea1" class="form-label">關於我</label>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name = 'about_me'>{{ form_about_me }}</textarea>
              </div>
            <div class="col-12">
                <button type="button" class="btn btn-info" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    送出
                </button>

                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">修改會員資料</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                        確定要修改嗎?
                        </div>
                        <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">取消</button>
                        <button type="submit" class="btn btn-primary">確定</button>
                        </div>
                    </div>
                    </div>
                </div>
            
            </div>
        </form>
    </div>
{% endblock %}

app/templates/main/index.html
<!-- 

    主頁面
    
    created date : 2021/10/05
    created by : jay

    last update date : 2021/10/26
    update by : jay

-->

{% extends 'basic.html' %} 
{% import 'main/_macros.html' as macros %} 

{% block head %} 
  {{ super() }}
  <link href="{{ url_for('static', filename = 'css/index.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename = 'css/post.css') }}" rel="stylesheet">
{% endblock %}

{% block title %} Daily Life index {% endblock %}

{% block page_content %} 
  <div class="page-header">
    {% if current_user.is_authenticated %} 
    <h1>Hello {{ current_user.username }}</h1>
    {% else %}
    <h1>Daily Life 分享你的日常點滴</h1> 
    {% endif %}
  </div>
  <div class="page">
    {% if current_user.is_authenticated %}
    <div class="form-content">
      <form class="row g-3" action="{{ url_for('main.index') }}" method="POST">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <div class="mb-3 row">
            <label for="exampleFormControlTextarea1" class="form-label">在想什麼</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name = 'post' required></textarea>
        </div>
          <div class="form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1" name="is_private">
            <label class="form-check-label" for="exampleCheck1" title="設為私人貼文代表只有本人能看到貼文">設為私人貼文</label>
          </div>
          <div class="mb-3">
            <button class="btn btn-primary" type="submit">送出</button>
          </div>
      </form> 
    </div>
    {% endif %}

    {% if pagination %} 
        <div class="pagination-content">
          {{ macros.pagination_widget(pagination, '.index', is_top = True) }}
        </div>
    {% endif %}

    {% if current_user.is_authenticated %}
    <div class="post-tab">
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <a class="nav-link {% if show_posts == 'all' %} active {% endif %}" aria-current="page" href="{{ url_for('main.show_all_posts') }}">All</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if show_posts == 'following' %} active {% endif %}" href="{{ url_for('main.following_posts') }}">Following</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if show_posts == 'private' %} active {% endif %}" href="{{ url_for('main.private_posts') }}">Private</a>
        </li>
      </ul>
    </div>
    {% endif %}

    <div class="posts-content">
      {% include 'main/_post.html' %}
    </div>

    {% if pagination %} 
        <div class="pagination-content">
          {{ macros.pagination_widget(pagination, '.index') }}
        </div>
    {% endif %}
  </div>
  
{% endblock %}

app/templates/main/search.html
{% extends 'basic.html' %} 

{% block head %} 
    {{ super() }}
    <link href="{{ url_for('static', filename = 'css/users.css') }}" rel="stylesheet">
{% endblock %}
{% block page_content %} 
  <div class="page-header">
    <h1>搜尋結果</h1>
  </div>
  <div class="page">
    <div class="users-content">
      {% if users %} 
        {% include 'main/_user.html' %} 
      {% else %} 
        <h2> 沒有符合的結果 </h2>
      {% endif %}
      </div>
  </div>
  
{% endblock %}

app/templates/main/user.html
<!--

    使用者個人資訊頁面
    
    created date : 2021/10/21
    created by : jay

    update date : 2021/10/26
    update by : jay


-->

{% extends 'basic.html' %} 

{% block head %} 
  {{ super() }}
  <link href="{{ url_for('static', filename = 'css/post.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename = 'css/user.css') }}" rel="stylesheet">
{% endblock %}

{% block title %} User Info {% endblock %} 

{% block page_content %} 
    <div class="page-header">
        <h1> {{ user.username }} 的個人資料</h1>
          
    </div>

    <div class="page">
        <div class="user-profile">
            <div class="profile-img">
                <img src="{{ user.gravatar(size = 300) }}" class="rounded-circle"> <br>
            </div>
            
            <div class="user-info">
                {% if user.name or user.location %} 
                    <p>
                        {% if user.name %}
                            <h2>
                            {{ user.name }}
                            </h2> 
                        {% endif %}
                        {% if user.location %} 
                            來自 <a href="http://maps.google.com/?q={{ user.location }}" target="_blank"> {{ user.location }}</a>
                        {% endif %} 
                    </p> 
                {% endif %}
                {% if current_user.is_administrator() %} 
                        <p>
                            Email:
                            <a href="mailto:{{ user.email }}">{{ user.email }}</a>
                        </p>
                {% endif %}
                {% if user.about_me %} 
                    <p>
                        {{ user.about_me }}
                    </p>
                {% endif %}
                <p>
                    從 {{ moment(user.member_since).format('LL') }} 加入 <br>
                    上次登入是 {{ moment(user.last_seen).fromTime(now) }}
                </p>
                <p>
                    {% if current_user.can(Permission.FOLLOW) and user != current_user %} 
                        {% if not current_user.is_following(user) %}
                            <button type="button" class="btn btn-info">
                                <a href="{{ url_for('main.follow', username = user.username) }}">Follow</a>
                            </button>    
                            
                        {% else %} 
                            <button type="button" class="btn btn-danger">
                                <a href="{{ url_for('main.unfollow', username = user.username) }}">Unfollow</a>
                            </button>
                            
                        {% endif %}
                    {% endif %}

                    <a href="{{ url_for('main.following', username = user.username) }}">
                        Following: <span class="badge bg-primary rounded-pil">{{ user.following.count() }}</span>
                    </a>
                    <a href="{{ url_for('main.followers', username = user.username) }}">
                        Followers: <span class="badge bg-primary rounded-pil">{{ user.followers.count() }}</span>
                    </a>

                    {% if current_user.is_authenticated and user != current_user and user.is_following(current_user) %} 
                        | <span class="badge rounded-pill bg-info text-dark">Follow You</span>
                    {% endif %}
                </p>
                <div class="user-btn">
                    {% if current_user == user %}
                        <a href="{{ url_for('main.edit_profile') }}">
                            <button type="button" class="btn btn-outline-primary">編輯個人資料</button>    
                        </a>
                    {% endif %}

                    {% if current_user.is_administrator() %}
                        <a href="{{ url_for('main.edit_profile_admin', id = user.id ) }}">
                            <button type="button" class="btn btn-outline-danger">編輯使用者資訊 [Admin]</button>
                        </a>
                    {% endif %}
                </div>
                

            </div>
            
        </div>
        
        <div class="user-posts">
            <h3>{{ user.username }} 的貼文</h3>
            {% include 'main/_post.html' %}
        </div>
    </div>
{% endblock %}